/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Smartphone;

import AssistanceTouristique.ServiceAchatOfficePackage.achatImpossibleException;
import AssistanceTouristique.ServiceBancairePackage.operationImpossibleException;
import Office.ClientOffice;
import Office.ServiceAchatOfficeImpl;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pc-jfred
 */
public class ClientSmartphone extends javax.swing.JFrame {

    /**
     * Creates new form MainSmartphone
     */
    public static AssistanceTouristique.Office monOffice;
    public static AssistanceTouristique.ServiceAchatOffice monServAchat;
    public static AssistanceTouristique.ServiceBancaire monServBancaire;
    public static String dd, df;
    public static Float montant;
    
    public ClientSmartphone() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bandeauPanel = new javax.swing.JPanel();
        ImageBandeau = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        boutonRetour = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        EcranIdentification = new javax.swing.JPanel();
        labelIdentifiant = new javax.swing.JLabel();
        fieldIdentifiant = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        boutonSeConnecter = new javax.swing.JButton();
        jScrollPaneIdentification = new javax.swing.JScrollPane();
        jTextPaneIdentification = new javax.swing.JTextPane();
        boutonInscription = new javax.swing.JButton();
        boutonMotDePasseOublie = new javax.swing.JButton();
        EcranAccueil = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        boutonReserver = new javax.swing.JButton();
        EcranInfoSite = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        labelIdentifiant1 = new javax.swing.JLabel();
        labelIdentifiant2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelIdentifiant3 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        EcranBilletterie = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        EcranRecherche = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        EcranAchat = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dateD = new javax.swing.JFormattedTextField();
        dateF = new javax.swing.JFormattedTextField();
        BoutonPayer = new javax.swing.JButton();
        textMontant = new javax.swing.JLabel();
        EcranBanque = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        BoutonValiderPaiement = new javax.swing.JButton();
        inputCarteBancaire = new javax.swing.JTextField();
        inputMontant = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        footerPanel = new javax.swing.JPanel();
        boutonAccueil = new javax.swing.JButton();
        boutonBilletterie = new javax.swing.JButton();
        boutonRecherche = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SmartPhone");
        setResizable(false);

        ImageBandeau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/bandeau.jpg"))); // NOI18N

        javax.swing.GroupLayout bandeauPanelLayout = new javax.swing.GroupLayout(bandeauPanel);
        bandeauPanel.setLayout(bandeauPanelLayout);
        bandeauPanelLayout.setHorizontalGroup(
            bandeauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bandeauPanelLayout.createSequentialGroup()
                .addComponent(ImageBandeau)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bandeauPanelLayout.setVerticalGroup(
            bandeauPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ImageBandeau)
        );

        headerPanel.setBackground(new java.awt.Color(0, 0, 0));
        headerPanel.setMaximumSize(new java.awt.Dimension(325, 50));
        headerPanel.setMinimumSize(new java.awt.Dimension(325, 50));
        headerPanel.setPreferredSize(new java.awt.Dimension(325, 50));

        boutonRetour.setBackground(new java.awt.Color(102, 102, 102));
        boutonRetour.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        boutonRetour.setForeground(new java.awt.Color(255, 255, 255));
        boutonRetour.setText("Retour");
        boutonRetour.setVisible(false);
        boutonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRetourActionPerformed(evt);
            }
        });

        labelLogo.setFont(new java.awt.Font("Brush Script MT", 0, 24)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 0, 0));
        labelLogo.setText("Ticket'Me !");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonRetour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonRetour)
                    .addComponent(labelLogo))
                .addGap(14, 14, 14))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(325, 361));
        mainPanel.setMinimumSize(new java.awt.Dimension(325, 361));
        mainPanel.setPreferredSize(new java.awt.Dimension(325, 361));
        mainPanel.setLayout(new java.awt.CardLayout());

        EcranIdentification.setBackground(new java.awt.Color(255, 255, 255));

        labelIdentifiant.setBackground(new java.awt.Color(153, 153, 153));
        labelIdentifiant.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelIdentifiant.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentifiant.setText("   Identifiant *");
        labelIdentifiant.setToolTipText("");
        labelIdentifiant.setOpaque(true);

        fieldIdentifiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdentifiantActionPerformed(evt);
            }
        });

        labelPassword.setBackground(new java.awt.Color(153, 153, 153));
        labelPassword.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(255, 255, 255));
        labelPassword.setText("   Mot de passe *");
        labelPassword.setToolTipText("");
        labelPassword.setOpaque(true);

        boutonSeConnecter.setBackground(new java.awt.Color(0, 51, 255));
        boutonSeConnecter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonSeConnecter.setForeground(new java.awt.Color(255, 255, 255));
        boutonSeConnecter.setText("Se connecter");
        boutonSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSeConnecterActionPerformed(evt);
            }
        });

        jScrollPaneIdentification.setBorder(null);

        jTextPaneIdentification.setEditable(false);
        jTextPaneIdentification.setBorder(null);
        jTextPaneIdentification.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextPaneIdentification.setText("Pour accéder à l'application, acheter des billets et récupérer les billets pour vos prochaines sorties, vous devez vous identifier.");
        jTextPaneIdentification.setAutoscrolls(false);
        jTextPaneIdentification.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextPaneIdentification.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextPaneIdentification.setFocusable(false);
        jTextPaneIdentification.setHighlighter(null);
        jTextPaneIdentification.setRequestFocusEnabled(false);
        jTextPaneIdentification.setVerifyInputWhenFocusTarget(false);
        jScrollPaneIdentification.setViewportView(jTextPaneIdentification);

        boutonInscription.setBackground(new java.awt.Color(0, 51, 255));
        boutonInscription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boutonInscription.setForeground(new java.awt.Color(255, 255, 255));
        boutonInscription.setText("S'incrire");
        boutonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonInscriptionActionPerformed(evt);
            }
        });

        boutonMotDePasseOublie.setBackground(new java.awt.Color(0, 51, 255));
        boutonMotDePasseOublie.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        boutonMotDePasseOublie.setForeground(new java.awt.Color(255, 255, 255));
        boutonMotDePasseOublie.setText("Mot de passe oublié");
        boutonMotDePasseOublie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMotDePasseOublieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EcranIdentificationLayout = new javax.swing.GroupLayout(EcranIdentification);
        EcranIdentification.setLayout(EcranIdentificationLayout);
        EcranIdentificationLayout.setHorizontalGroup(
            EcranIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIdentifiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EcranIdentificationLayout.createSequentialGroup()
                .addComponent(jScrollPaneIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(EcranIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EcranIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranIdentificationLayout.createSequentialGroup()
                        .addGroup(EcranIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranIdentificationLayout.createSequentialGroup()
                        .addGroup(EcranIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boutonInscription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boutonSeConnecter, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(boutonMotDePasseOublie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
        );
        EcranIdentificationLayout.setVerticalGroup(
            EcranIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranIdentificationLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPaneIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(fieldIdentifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(boutonSeConnecter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonInscription)
                .addGap(18, 18, 18)
                .addComponent(boutonMotDePasseOublie)
                .addGap(0, 67, Short.MAX_VALUE))
        );

        mainPanel.add(EcranIdentification, "EcranIdentification");
        EcranIdentification.getAccessibleContext().setAccessibleName("");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/721-museum-toulouse - Copie.jpg"))); // NOI18N
        jButton1.setText("Muséum d'histoire naturelle de Toulouse");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/company_logo45x45.jpg"))); // NOI18N
        jButton2.setText("Musée des Augustins - Musée des beaux arts de Toulouse");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/hg-deportation45x45.jpg"))); // NOI18N
        jButton3.setText("Musée de la résistance et de la déportation");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/hg-labit45x45.jpg"))); // NOI18N
        jButton4.setText("Musée Georges-Labit ");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/4385_20090101171725.jpg"))); // NOI18N
        jButton5.setText("Musée Saint-Raymond de Toulouse");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        boutonReserver.setText("Réserver");
        boutonReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonReserverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EcranAccueilLayout = new javax.swing.GroupLayout(EcranAccueil);
        EcranAccueil.setLayout(EcranAccueilLayout);
        EcranAccueilLayout.setHorizontalGroup(
            EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonReserver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EcranAccueilLayout.createSequentialGroup()
                        .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranAccueilLayout.createSequentialGroup()
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(EcranAccueilLayout.createSequentialGroup()
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(EcranAccueilLayout.createSequentialGroup()
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EcranAccueilLayout.createSequentialGroup()
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EcranAccueilLayout.createSequentialGroup()
                                .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        EcranAccueilLayout.setVerticalGroup(
            EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boutonReserver, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        mainPanel.add(EcranAccueil, "EcranAccueil");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Smartphone/Images/721-museum-toulouse100x100.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Muséum d'histoires naturelles");

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Prix : 8 €");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setFocusable(false);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTextPane1.setText("Au gré de plusieurs espaces thématiques, l'exposition permanente du Muséum meet en exergue la richesse et la profondeur des relations liant l'Homme et la Nature. L'Homme depuis sa naissance jusqu'à son avenir, en passant par les différentes étapes de son évolution est ainsi amené à s'interroger, réfléchir, jusqu'à prendre conscience des défis contemporains posés à l'humanité.");
        jTextPane1.setFocusable(false);
        jTextPane1.setHighlighter(null);
        jScrollPane1.setViewportView(jTextPane1);

        labelIdentifiant1.setBackground(new java.awt.Color(153, 153, 153));
        labelIdentifiant1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelIdentifiant1.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentifiant1.setText("   Présentation");
        labelIdentifiant1.setToolTipText("");
        labelIdentifiant1.setOpaque(true);

        labelIdentifiant2.setBackground(new java.awt.Color(153, 153, 153));
        labelIdentifiant2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelIdentifiant2.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentifiant2.setText("   Adresse");
        labelIdentifiant2.setToolTipText("");
        labelIdentifiant2.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setText("Musée nationnal - Sciences");

        jLabel5.setText("35 Allée Jules Guesde Toulouse");

        jLabel6.setText("05 67 73 84 84");

        labelIdentifiant3.setBackground(new java.awt.Color(153, 153, 153));
        labelIdentifiant3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        labelIdentifiant3.setForeground(new java.awt.Color(255, 255, 255));
        labelIdentifiant3.setText("   Affluence");
        labelIdentifiant3.setToolTipText("");
        labelIdentifiant3.setOpaque(true);

        jProgressBar1.setForeground(new java.awt.Color(51, 255, 51));
        jProgressBar1.setValue(14);

        javax.swing.GroupLayout EcranInfoSiteLayout = new javax.swing.GroupLayout(EcranInfoSite);
        EcranInfoSite.setLayout(EcranInfoSiteLayout);
        EcranInfoSiteLayout.setHorizontalGroup(
            EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelIdentifiant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(labelIdentifiant2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EcranInfoSiteLayout.createSequentialGroup()
                .addGroup(EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(labelIdentifiant3, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
            .addGroup(EcranInfoSiteLayout.createSequentialGroup()
                .addGroup(EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranInfoSiteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(EcranInfoSiteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EcranInfoSiteLayout.setVerticalGroup(
            EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranInfoSiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EcranInfoSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EcranInfoSiteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdentifiant1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdentifiant2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIdentifiant3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainPanel.add(EcranInfoSite, "EcranInfoSite");

        jLabel7.setText("Ici la billetterie !");

        javax.swing.GroupLayout EcranBilletterieLayout = new javax.swing.GroupLayout(EcranBilletterie);
        EcranBilletterie.setLayout(EcranBilletterieLayout);
        EcranBilletterieLayout.setHorizontalGroup(
            EcranBilletterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranBilletterieLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel7)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        EcranBilletterieLayout.setVerticalGroup(
            EcranBilletterieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranBilletterieLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel7)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        mainPanel.add(EcranBilletterie, "EcranBilletterie");

        jLabel8.setText("Ici la recherche !");

        javax.swing.GroupLayout EcranRechercheLayout = new javax.swing.GroupLayout(EcranRecherche);
        EcranRecherche.setLayout(EcranRechercheLayout);
        EcranRechercheLayout.setHorizontalGroup(
            EcranRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranRechercheLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel8)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        EcranRechercheLayout.setVerticalGroup(
            EcranRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranRechercheLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel8)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        mainPanel.add(EcranRecherche, "EcranRecherche");

        jLabel9.setText("Date de début :");

        jLabel10.setText("Date de fin :");

        jLabel11.setText("Montant :");

        dateD.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dateD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateDActionPerformed(evt);
            }
        });

        dateF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dateF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFActionPerformed(evt);
            }
        });

        BoutonPayer.setText("Payer");
        BoutonPayer.setActionCommand("BoutonPayer");
        BoutonPayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonPayerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EcranAchatLayout = new javax.swing.GroupLayout(EcranAchat);
        EcranAchat.setLayout(EcranAchatLayout);
        EcranAchatLayout.setHorizontalGroup(
            EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAchatLayout.createSequentialGroup()
                .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranAchatLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranAchatLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(42, 42, 42))
                            .addGroup(EcranAchatLayout.createSequentialGroup()
                                .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateD)
                            .addComponent(dateF)
                            .addComponent(textMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EcranAchatLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(BoutonPayer)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        EcranAchatLayout.setVerticalGroup(
            EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranAchatLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(dateD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(dateF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(EcranAchatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(BoutonPayer)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        BoutonPayer.getAccessibleContext().setAccessibleName("BoutonPayer");

        mainPanel.add(EcranAchat, "EcranAchat");
        EcranAchat.getAccessibleContext().setAccessibleName("");

        jLabel12.setText("Paiement de la commande");

        jLabel14.setText("Numéro de carte bancaire :");

        BoutonValiderPaiement.setText("Valider");
        BoutonValiderPaiement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderPaiementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EcranBanqueLayout = new javax.swing.GroupLayout(EcranBanque);
        EcranBanque.setLayout(EcranBanqueLayout);
        EcranBanqueLayout.setHorizontalGroup(
            EcranBanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranBanqueLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(EcranBanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranBanqueLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(inputMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(EcranBanqueLayout.createSequentialGroup()
                .addGroup(EcranBanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranBanqueLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(inputCarteBancaire))
                    .addGroup(EcranBanqueLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel12)
                        .addGap(0, 92, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(EcranBanqueLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(BoutonValiderPaiement)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EcranBanqueLayout.setVerticalGroup(
            EcranBanqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranBanqueLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addComponent(inputMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCarteBancaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(BoutonValiderPaiement)
                .addGap(41, 41, 41))
        );

        inputMontant.getAccessibleContext().setAccessibleName("inputMontant");

        mainPanel.add(EcranBanque, "EcranBanque");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel8, "card9");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel9, "card10");

        footerPanel.setBackground(new java.awt.Color(255, 255, 255));
        footerPanel.setMaximumSize(new java.awt.Dimension(325, 50));
        footerPanel.setMinimumSize(new java.awt.Dimension(325, 50));
        footerPanel.setPreferredSize(new java.awt.Dimension(325, 50));

        boutonAccueil.setBackground(new java.awt.Color(100, 100, 100));
        boutonAccueil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonAccueil.setForeground(new java.awt.Color(255, 255, 255));
        boutonAccueil.setText("Accueil");
        boutonAccueil.setPreferredSize(new java.awt.Dimension(80, 23));
        boutonAccueil.setVisible(false);
        boutonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAccueilActionPerformed(evt);
            }
        });

        boutonBilletterie.setBackground(new java.awt.Color(0, 0, 0));
        boutonBilletterie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonBilletterie.setForeground(new java.awt.Color(204, 204, 204));
        boutonBilletterie.setText("Billetterie");
        boutonBilletterie.setPreferredSize(new java.awt.Dimension(80, 23));
        boutonBilletterie.setVisible(false);
        boutonBilletterie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonBilletterieActionPerformed(evt);
            }
        });

        boutonRecherche.setBackground(new java.awt.Color(0, 0, 0));
        boutonRecherche.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonRecherche.setForeground(new java.awt.Color(204, 204, 204));
        boutonRecherche.setText("Recherche");
        boutonRecherche.setPreferredSize(new java.awt.Dimension(80, 23));
        boutonRecherche.setVisible(false);
        boutonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addComponent(boutonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(boutonBilletterie, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(boutonRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boutonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonBilletterie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(boutonRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bandeauPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bandeauPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRetourActionPerformed
        // retour à l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranAccueil");
        boutonRetour.setVisible(false);
    }//GEN-LAST:event_boutonRetourActionPerformed

    private void boutonBilletterieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonBilletterieActionPerformed
        // on modifie l'affichage des autres bouton lors du clic sur le bouton courant
        boutonBilletterie.setBackground(new Color(100, 100, 100));
        boutonBilletterie.setForeground(new Color(255, 255, 255));
        boutonAccueil.setBackground(new Color(0, 0, 0));
        boutonAccueil.setForeground(new Color(180, 180, 180));
        boutonRecherche.setBackground(new Color(0, 0, 0));
        boutonRecherche.setForeground(new Color(180, 180, 180));
        
        //on masque le bouton retour
        boutonRetour.setVisible(false);
        
        //on affiche l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranBilletterie");
    }//GEN-LAST:event_boutonBilletterieActionPerformed

    private void boutonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAccueilActionPerformed
        // on modifie l'affichage des autres bouton lors du clic sur le bouton courant
        boutonAccueil.setBackground(new Color(100, 100, 100));
        boutonAccueil.setForeground(new Color(255, 255, 255));
        boutonBilletterie.setBackground(new Color(0, 0, 0));
        boutonBilletterie.setForeground(new Color(180, 180, 180));
        boutonRecherche.setBackground(new Color(0, 0, 0));
        boutonRecherche.setForeground(new Color(180, 180, 180));
        
        //on masque le bouton retour
        boutonRetour.setVisible(false);
        
        //on affiche l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranAccueil");
    }//GEN-LAST:event_boutonAccueilActionPerformed

    private void boutonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRechercheActionPerformed
        // on modifie l'affichage des autres bouton lors du clic sur le bouton courant
        boutonRecherche.setBackground(new Color(100, 100, 100));
        boutonRecherche.setForeground(new Color(255, 255, 255));
        boutonBilletterie.setBackground(new Color(0, 0, 0));
        boutonBilletterie.setForeground(new Color(180, 180, 180));
        boutonAccueil.setBackground(new Color(0, 0, 0));
        boutonAccueil.setForeground(new Color(180, 180, 180));
        
        //on masque le bouton retour
        boutonRetour.setVisible(false);
        
        //on affiche l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranRecherche");
    }//GEN-LAST:event_boutonRechercheActionPerformed

    private void boutonMotDePasseOublieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMotDePasseOublieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonMotDePasseOublieActionPerformed

    private void boutonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonInscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonInscriptionActionPerformed

    private void boutonSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSeConnecterActionPerformed
        System.out.println(fieldPassword.getPassword().toString());
        //vérification des données de connection ...
        if(fieldIdentifiant.getText().equals("") && String.valueOf(fieldPassword.getPassword()).equals(""))
        {
            // si l'identification est ok ...
            System.out.println("Connexion réussie !");
            CardLayout card = (CardLayout) mainPanel.getLayout();
            card.show(mainPanel, "EcranAccueil");
            footerPanel.setBackground(new Color(0,0,0));
            boutonAccueil.setVisible(true);
            boutonBilletterie.setVisible(true);
            boutonRecherche.setVisible(true);
        }
        else{
            //on affiche une pop-up d'erreur et on vide les champs de saisie
            System.out.println("Echec d'authentification !");
            JOptionPane.showMessageDialog(this, "Erreur d'authentification : \nPseudo et/ou mot de passe incorrect", "Erreur", JOptionPane.WARNING_MESSAGE);
            fieldIdentifiant.setText("");
            fieldPassword.setText("");
        }

    }//GEN-LAST:event_boutonSeConnecterActionPerformed

    private void fieldIdentifiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdentifiantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdentifiantActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //On affiche les Infos du Site
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranInfoSite");
        //On rend le bouton Retour visible
        boutonRetour.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boutonReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonReserverActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranAchat");
    }//GEN-LAST:event_boutonReserverActionPerformed

    private void BoutonPayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonPayerActionPerformed
         // TODO add your handling code here:
        //Je récupère les dates
        dd=dateD.getText();
        df=dateF.getText();
        montant=Float.parseFloat(textMontant.getText());
        
        //Appel au serveur du service achat de l'office
        Office.ServeurServiceAchatOffice serveur_achat = new Office.ServeurServiceAchatOffice(monServAchat, dd, df, montant);
        
        //Affichage de l'écran informations bancaires
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranBanque");
        
        try {
            //appel de la fonction acheter prestation
            //AssistanceTouristique.Carte c = monServAchat.acheterPrestation(dd, df, Float.parseFloat(textMontant.getText()));
            AssistanceTouristique.Carte c = serveur_achat.getServiceAchat().acheterPrestation(dd, df, Float.parseFloat(textMontant.getText()));
            //System.out.println(c.dateDebut+" "+c.dateFin);
        } catch (achatImpossibleException ex) {
            Logger.getLogger(ClientSmartphone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BoutonPayerActionPerformed

    private void dateDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateDActionPerformed
        // TODO add your handling code here:
         DateFormat formater = DateFormat.getDateInstance(DateFormat.SHORT,Locale.FRANCE);

        //Récupération de la date de début
        Date dd, df;
        try {
            dd = formater.parse(dateD.getText());
            df = formater.parse(dateF.getText());
            final long CONST_DURATION_OF_DAY = 1000 * 60 * 60 * 24; 

            long diff = Math.abs(df.getTime() - dd.getTime());
            long nb_jour = (long)diff/CONST_DURATION_OF_DAY;
            
            //Calcul du montant en fonction du nombre de jours (5 euros par jour)
            long montant=(nb_jour*5)+1;
            System.out.println(String.valueOf(montant));
            
            //J'affiche la valeur du montant dans l'input du montant
            textMontant.setText(String.valueOf(montant));

        } catch (ParseException ex) {
            Logger.getLogger(ClientSmartphone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateDActionPerformed

    private void dateFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFActionPerformed
        // TODO add your handling code here:
        DateFormat formater = DateFormat.getDateInstance(DateFormat.SHORT,Locale.FRANCE);

        //Récupération de la date de début
        Date dd, df;
        try {
            dd = formater.parse(dateD.getText());
            df = formater.parse(dateF.getText());
            final long CONST_DURATION_OF_DAY = 1000 * 60 * 60 * 24; 

            long diff = Math.abs(df.getTime() - dd.getTime());
            long nb_jour = (long)diff/CONST_DURATION_OF_DAY;
            
            //Calcul du montant en fonction du nombre de jours (5 euros par jour)
            long montant=(nb_jour*5)+5;
  
            //J'affiche la valeur du montant dans l'input du montant
            textMontant.setText(String.valueOf(montant));

        } catch (ParseException ex) {
            Logger.getLogger(ClientSmartphone.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateFActionPerformed

    private void BoutonValiderPaiementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderPaiementActionPerformed
        // TODO add your handling code here:
        AutresServices.ServeurServiceBancaire servBanque = new AutresServices.ServeurServiceBancaire(monServBancaire);
        try {
            boolean reponse = servBanque.getServiceBancaire().verifierPaiement(montant);
            
        } catch (operationImpossibleException ex) {
            Logger.getLogger(ClientSmartphone.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_BoutonValiderPaiementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        String nom_office;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSmartphone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
          //Flux E/S standards
        BufferedReader entree_std = new BufferedReader(new InputStreamReader(System.in));
        PrintStream sortie_std = new PrintStream(System.out);
        
         try {
            //Configuration de base
            sortie_std.print("Client smartphone: quel est le nom de l'office :");
            nom_office = entree_std.readLine();
            
            //1
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, null);
            
            //2 
            //org.omg.CosNaming.NamingContext nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            org.omg.CosNaming.NamingContext nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.string_to_object("corbaloc:iiop:1.2@127.0.0.1:2001/NameService"));
            
            //Recherche de l'office
            org.omg.CosNaming.NameComponent[] office = new org.omg.CosNaming.NameComponent[1];
            office[0] = new org.omg.CosNaming.NameComponent(nom_office, "");
            org.omg.CORBA.Object distantOffice = nameRoot.resolve(office);
            
            //3
            monServAchat = AssistanceTouristique.ServiceAchatOfficeHelper.narrow(distantOffice);
            monServBancaire = AssistanceTouristique.ServiceBancaireHelper.narrow(distantOffice);
                        
           //Appel à l'interfca graphique
           new ClientSmartphone().setVisible(true);
           
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonPayer;
    private javax.swing.JButton BoutonValiderPaiement;
    private javax.swing.JPanel EcranAccueil;
    private javax.swing.JPanel EcranAchat;
    private javax.swing.JPanel EcranBanque;
    private javax.swing.JPanel EcranBilletterie;
    private javax.swing.JPanel EcranIdentification;
    private javax.swing.JPanel EcranInfoSite;
    private javax.swing.JPanel EcranRecherche;
    private javax.swing.JLabel ImageBandeau;
    private javax.swing.JPanel bandeauPanel;
    private javax.swing.JButton boutonAccueil;
    private javax.swing.JButton boutonBilletterie;
    private javax.swing.JButton boutonInscription;
    private javax.swing.JButton boutonMotDePasseOublie;
    private javax.swing.JButton boutonRecherche;
    private javax.swing.JButton boutonReserver;
    private javax.swing.JButton boutonRetour;
    private javax.swing.JButton boutonSeConnecter;
    private javax.swing.JFormattedTextField dateD;
    private javax.swing.JFormattedTextField dateF;
    private javax.swing.JTextField fieldIdentifiant;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField inputCarteBancaire;
    private javax.swing.JLabel inputMontant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneIdentification;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPaneIdentification;
    private javax.swing.JLabel labelIdentifiant;
    private javax.swing.JLabel labelIdentifiant1;
    private javax.swing.JLabel labelIdentifiant2;
    private javax.swing.JLabel labelIdentifiant3;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel textMontant;
    // End of variables declaration//GEN-END:variables
}
