/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SiteSaintRaymond;

import SiteMuseum.*;
import SiteGeorgesLabit.*;
import Site.*;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;

/**
 *
 * @author Lydia
 */
public class ClientSiteSaintRaymond extends javax.swing.JFrame {
    private static String nomSite="Saint Raymond";
    private static org.omg.CosNaming.NamingContext nameRoot;
    /**
     * Creates new form ClientSite
     */
    public ClientSiteSaintRaymond() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Accueil = new javax.swing.JPanel();
        jLabelTitreAccueil = new javax.swing.JLabel();
        jButtonConsulterStats = new javax.swing.JButton();
        EcranStats = new javax.swing.JPanel();
        jButtonAccueil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jLabelStatistique = new javax.swing.JLabel();
        jLabelDateStat = new javax.swing.JLabel();
        jFormattedTextFieldDateStat = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabelTitreAccueil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreAccueil.setText("Musée Saint Raymond");

        jButtonConsulterStats.setText("Consulter les statistiques");
        jButtonConsulterStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsulterStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AccueilLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButtonConsulterStats)
                .addContainerGap(340, Short.MAX_VALUE))
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAccueil)
                .addGap(93, 93, 93)
                .addComponent(jButtonConsulterStats)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        mainPanel.add(Accueil, "Accueil");

        EcranStats.setPreferredSize(new java.awt.Dimension(800, 600));

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTableStats);

        jLabelStatistique.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatistique.setText("Statistiques du musée:");

        jLabelDateStat.setText("Consulter les statistiques à partir de :");

        jFormattedTextFieldDateStat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldDateStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDateStatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EcranStatsLayout = new javax.swing.GroupLayout(EcranStats);
        EcranStats.setLayout(EcranStatsLayout);
        EcranStatsLayout.setHorizontalGroup(
            EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranStatsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranStatsLayout.createSequentialGroup()
                        .addComponent(jLabelDateStat)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldDateStat, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                            .addComponent(jButtonAccueil)
                            .addGap(49, 49, 49))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(179, 179, 179)))))
        );
        EcranStatsLayout.setVerticalGroup(
            EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAccueil)
                .addGap(72, 72, 72)
                .addComponent(jLabelStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateStat)
                    .addComponent(jFormattedTextFieldDateStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        mainPanel.add(EcranStats, "EcranStats");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
        );

        mainPanel.add(jPanel1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsulterStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsulterStatsActionPerformed
        //Affichage de l'écran informations bancaires
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranStats");
    }//GEN-LAST:event_jButtonConsulterStatsActionPerformed

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        //Affichage de l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "Accueil");
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jFormattedTextFieldDateStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDateStatActionPerformed
        String nomServiceStat = ServeurStatSaintRaymond.nomServiceStatSite;
        String date = jFormattedTextFieldDateStat.getText();
        String valeurStat;
        
        try {
            /********* Appel au service statistique du site *********/
            // Construction du nom a rechercher
             org.omg.CosNaming.NameComponent[] nameToFind = new org.omg.CosNaming.NameComponent[1];
             nameToFind[0] = new org.omg.CosNaming.NameComponent(nomServiceStat,"");

            // Recherche aupres du naming service
            org.omg.CORBA.Object distantServiceStat = nameRoot.resolve(nameToFind);
            System.out.println("Objet '" + nomServiceStat + "' trouve aupres du service de noms. IOR de l'objet :");
          
            // Casting de l'objet CORBA
            AssistanceTouristique.ServiceStatSite monServiceStat = AssistanceTouristique.ServiceStatSiteHelper.narrow(distantServiceStat);
            
            //Récupération des statistiques auprès du service stat
            AssistanceTouristique.Statistique[] stat = monServiceStat.getStatsSite(date, nomSite);
            
            /************ Remplissage du tableau *************/
            //Première ligne
            jTableStats.getModel().setValueAt(stat[0].libelleStat,0,0);
            valeurStat=stat[0].valeurStat + " " + stat[0].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,0,1);
            
            //Deuxième ligne
            jTableStats.getModel().setValueAt(stat[1].libelleStat,1,0);
            valeurStat=stat[1].valeurStat + " " + stat[1].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,1,1);
            
            //Troisième ligne
            jTableStats.getModel().setValueAt(stat[2].libelleStat,2,0);
            valeurStat=stat[2].valeurStat + " " + stat[2].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,2,1);
            
            //Quatrième ligne
            jTableStats.getModel().setValueAt(stat[3].libelleStat,3,0);
            valeurStat=stat[3].valeurStat + " " + stat[3].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,3,1);                
            
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jFormattedTextFieldDateStatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSiteSaintRaymond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSiteSaintRaymond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSiteSaintRaymond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSiteSaintRaymond.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            //1
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, null);
            
            //2 
            nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            //org.omg.CosNaming.NamingContext nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.string_to_object("corbaloc:iiop:1.2@127.0.0.1:2001/NameService"));
            
            //Appel à l'interface graphique
            new ClientSiteSaintRaymond().setVisible(true);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel EcranStats;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonConsulterStats;
    private javax.swing.JFormattedTextField jFormattedTextFieldDateStat;
    private javax.swing.JLabel jLabelDateStat;
    private javax.swing.JLabel jLabelStatistique;
    private javax.swing.JLabel jLabelTitreAccueil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStats;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
