/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Office;

import java.awt.CardLayout;
import AssistanceTouristique.*;

/**
 *
 * @author jfred_000
 */
public class ClientOffice extends javax.swing.JFrame {
    private String nomOffice;
    private org.omg.CosNaming.NamingContext naming;
    
    public ClientOffice(String nomOffice, org.omg.CosNaming.NamingContext nameRoot) {
        this.nomOffice = nomOffice;
        this.naming = nameRoot;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BandeauOffice = new javax.swing.JPanel();
        jLabelTitreClientOffice = new javax.swing.JLabel();
        boutonAccueil = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        Accueil = new javax.swing.JPanel();
        boutonConsulterStatsSites = new javax.swing.JButton();
        boutonConsulterListeSites = new javax.swing.JButton();
        ConsultationVentes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListeVentes = new javax.swing.JTable();
        ConsultationListeSites = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableListeSites = new javax.swing.JTable();
        ConsultationStatsSites = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStatistique = new javax.swing.JTable();
        jLabelStatistiques = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Office de tourisme de Toulouse");
        setFocusCycleRoot(false);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jLabelTitreClientOffice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitreClientOffice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreClientOffice.setText("Office de tourisme de " + nomOffice);

        boutonAccueil.setText("Accueil");
        boutonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAccueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BandeauOfficeLayout = new javax.swing.GroupLayout(BandeauOffice);
        BandeauOffice.setLayout(BandeauOfficeLayout);
        BandeauOfficeLayout.setHorizontalGroup(
            BandeauOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BandeauOfficeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boutonAccueil)
                .addContainerGap())
            .addGroup(BandeauOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BandeauOfficeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTitreClientOffice, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        BandeauOfficeLayout.setVerticalGroup(
            BandeauOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BandeauOfficeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boutonAccueil)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(BandeauOfficeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BandeauOfficeLayout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jLabelTitreClientOffice)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        boutonConsulterStatsSites.setText("Consulter les statistiques des sites");
        boutonConsulterStatsSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConsulterStatsSitesActionPerformed(evt);
            }
        });

        boutonConsulterListeSites.setText("Consulter la liste des sites");
        boutonConsulterListeSites.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonConsulterListeSitesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addGroup(AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boutonConsulterStatsSites, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(boutonConsulterListeSites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(278, Short.MAX_VALUE))
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(boutonConsulterStatsSites)
                .addGap(28, 28, 28)
                .addComponent(boutonConsulterListeSites)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        mainPanel.add(Accueil, "Accueil");

        jLabel1.setText("Liste des ventes :");

        jTableListeVentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Client", "N° de carte"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableListeVentes);

        javax.swing.GroupLayout ConsultationVentesLayout = new javax.swing.GroupLayout(ConsultationVentes);
        ConsultationVentes.setLayout(ConsultationVentesLayout);
        ConsultationVentesLayout.setHorizontalGroup(
            ConsultationVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationVentesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(ConsultationVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultationVentesLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE))
                .addContainerGap())
        );
        ConsultationVentesLayout.setVerticalGroup(
            ConsultationVentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationVentesLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(ConsultationVentes, "ConsultationVentes");

        jTableListeSites.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Nom du site"
            }
        ));
        jScrollPane3.setViewportView(jTableListeSites);

        javax.swing.GroupLayout ConsultationListeSitesLayout = new javax.swing.GroupLayout(ConsultationListeSites);
        ConsultationListeSites.setLayout(ConsultationListeSitesLayout);
        ConsultationListeSitesLayout.setHorizontalGroup(
            ConsultationListeSitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationListeSitesLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        ConsultationListeSitesLayout.setVerticalGroup(
            ConsultationListeSitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultationListeSitesLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        mainPanel.add(ConsultationListeSites, "ConsultationListeSites");

        jTableStatistique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Site", "Taux de satisfaction", "Favori"
            }
        ));
        jScrollPane2.setViewportView(jTableStatistique);

        jLabelStatistiques.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatistiques.setText("Statistiques des sites :");

        javax.swing.GroupLayout ConsultationStatsSitesLayout = new javax.swing.GroupLayout(ConsultationStatsSites);
        ConsultationStatsSites.setLayout(ConsultationStatsSitesLayout);
        ConsultationStatsSitesLayout.setHorizontalGroup(
            ConsultationStatsSitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConsultationStatsSitesLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(ConsultationStatsSitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStatistiques)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        ConsultationStatsSitesLayout.setVerticalGroup(
            ConsultationStatsSitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultationStatsSitesLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jLabelStatistiques)
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        mainPanel.add(ConsultationStatsSites, "ConsultationStatsSites");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BandeauOffice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BandeauOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonConsulterStatsSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConsulterStatsSitesActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "ConsultationStatsSites");
        
        OfficeDBManager db = new OfficeDBManager();
        //Récupération de la liste des identifiants des sites de l'office
        short[] listeIdSites= db.getIdSites();
        ServiceESSite[] lesServES = new ServiceESSite[listeIdSites.length];
        String valeurStat;
        
        try {
            /****************** Recherche des Service ES des sites *******************/
            String nomServES;
            //Pour chaque site
            for(int i=0; i<listeIdSites.length; i++) {
                nomServES = "ES " + db.getCodeSite(listeIdSites[i]);

                org.omg.CosNaming.NameComponent[] nameToFind = new org.omg.CosNaming.NameComponent[1];
                nameToFind[0] = new org.omg.CosNaming.NameComponent(nomServES, "");
                org.omg.CORBA.Object distantServES = this.naming.resolve(nameToFind);
                System.out.println("Objet "+ nomServES + " trouvé auprès du service de noms.");
                
                lesServES[i] = ServiceESSiteHelper.narrow(distantServES);
                
                //Récupération du taux de satisfaction
                float tauxSatisfaction = lesServES[i].generateTauxSatisfaction();
                
                //Recupération du favoris
                boolean favoris = lesServES[i].generateEstFavoris();

                /************ Remplissage du tableau *************/
                //lignes
                jTableStatistique.getModel().setValueAt(db.getNomSite(listeIdSites[i]),i,0);
                valeurStat=tauxSatisfaction + " %";
                jTableStatistique.getModel().setValueAt(valeurStat,i,1);
                jTableStatistique.getModel().setValueAt(favoris,i,2);
            }
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_boutonConsulterStatsSitesActionPerformed

    private void boutonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAccueilActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "Accueil");
    }//GEN-LAST:event_boutonAccueilActionPerformed

    private void boutonConsulterListeSitesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonConsulterListeSitesActionPerformed
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "ConsultationListeSites");
        
         OfficeDBManager db = new OfficeDBManager();
        //Récupération de la liste des identifiants des sites de l'office
        short[] listeIdSites= db.getIdSites();
        
        //Pour chaque site
        for(int i=0; i<listeIdSites.length; i++) {
            /************ Remplissage du tableau *************/
                //lignes
                jTableListeSites.getModel().setValueAt(db.getCodeSite(listeIdSites[i]),i,0);
                jTableListeSites.getModel().setValueAt(db.getNomSite(listeIdSites[i]),i,1);
        }
        
        
    }//GEN-LAST:event_boutonConsulterListeSitesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //Lancement du serveur de l'office
       /* ServeurOffice servOffice = new ServeurOffice(args);
        Thread thread_servOffice = new Thread(servOffice);
        thread_servOffice.start();*/

        //Lancement du service stat de l'office
        /*ServeurStatOffice servStat = new ServeurStatOffice(nombd);
        Thread thread_servStat = new Thread(servStat);
        thread_servStat.start();
        
        //Lancement du service achat de l'office
        ServeurServiceAchatOffice servAchat = new ServeurServiceAchatOffice(nombd);
        Thread thread_servAchat = new Thread(servAchat);
        thread_servAchat.start();*/
    
        String nom_office=args[0];
        org.omg.CosNaming.NamingContext nameRoot;
        try {
            //1
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, null);
            
            //2 
            nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            
            //Appel à l'interface graphique
            new ClientOffice(nom_office, nameRoot).setVisible(true);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
        
        
      
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel BandeauOffice;
    private javax.swing.JPanel ConsultationListeSites;
    private javax.swing.JPanel ConsultationStatsSites;
    private javax.swing.JPanel ConsultationVentes;
    private javax.swing.JButton boutonAccueil;
    private javax.swing.JButton boutonConsulterListeSites;
    private javax.swing.JButton boutonConsulterStatsSites;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelStatistiques;
    private javax.swing.JLabel jLabelTitreClientOffice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableListeSites;
    private javax.swing.JTable jTableListeVentes;
    private javax.swing.JTable jTableStatistique;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
