/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Site;

import AssistanceTouristique.*;
import java.awt.CardLayout;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lydia
 */
public class ClientSiteTouristique extends javax.swing.JFrame {
    //TODO BD site GL
    private String nombd;
    //private static String nombd = "bd_site_histoirenaturelle";
    //private static String nombd = "bd_site_georgeslabit";
    //private static String nombd = "bd_site_saintraymond";
    public static boolean estPremierLancement = true;
    private static org.omg.CosNaming.NamingContext nameRoot;

    /*public static void setNombd(String str) {
        nombd = str;
    }*/
    
    /**
     * Creates new form ClientSite
     */
    public ClientSiteTouristique(String nombd) {
        this.nombd = nombd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Accueil = new javax.swing.JPanel();
        jLabelTitreAccueil = new javax.swing.JLabel();
        jButtonConsulterStats = new javax.swing.JButton();
        EcranInitialisationSite = new javax.swing.JPanel();
        jLabelTitreAssistant = new javax.swing.JLabel();
        jLabelSousTitreAssistant = new javax.swing.JLabel();
        jButtonValiderAssistant = new javax.swing.JButton();
        jTextFieldTitreSite = new javax.swing.JTextField();
        jTextFieldAdresseSite = new javax.swing.JTextField();
        jTextFieldNumTelSite = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescriptionSite = new javax.swing.JTextArea();
        jFormattedTextFieldHoraireOuvertureSite = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHoraireFermetureSite = new javax.swing.JFormattedTextField();
        jTextFieldLatitude = new javax.swing.JTextField();
        jTextFieldLongitude = new javax.swing.JTextField();
        jLabelHoraireOuverture = new javax.swing.JLabel();
        jLabelHoraireFermeture = new javax.swing.JLabel();
        EcranStats = new javax.swing.JPanel();
        jButtonAccueil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStats = new javax.swing.JTable();
        jLabelStatistique = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabelTitreAccueil.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTitreAccueil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreAccueil.setText(new SiteDBManager(nombd).getNomSite());

        jButtonConsulterStats.setText("Consulter les statistiques");
        jButtonConsulterStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsulterStatsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccueilLayout = new javax.swing.GroupLayout(Accueil);
        Accueil.setLayout(AccueilLayout);
        AccueilLayout.setHorizontalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(AccueilLayout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButtonConsulterStats)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        AccueilLayout.setVerticalGroup(
            AccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAccueil)
                .addGap(93, 93, 93)
                .addComponent(jButtonConsulterStats)
                .addContainerGap(460, Short.MAX_VALUE))
        );

        mainPanel.add(Accueil, "Accueil");

        jLabelTitreAssistant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitreAssistant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitreAssistant.setText("Assistant de premier lancement ...");

        jLabelSousTitreAssistant.setText("Bienvenue sur l'outil de gestion de site  ");

        jButtonValiderAssistant.setText("Valider");
        jButtonValiderAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderAssistantActionPerformed(evt);
            }
        });

        jTextFieldTitreSite.setText("titre du site ...");
        jTextFieldTitreSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldTitreSiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTitreSiteFocusLost(evt);
            }
        });

        jTextFieldAdresseSite.setText("adresse du site ...");
        jTextFieldAdresseSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAdresseSiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAdresseSiteFocusLost(evt);
            }
        });

        jTextFieldNumTelSite.setText("numéro de téléphone du site ...");
        jTextFieldNumTelSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNumTelSiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumTelSiteFocusLost(evt);
            }
        });

        jTextAreaDescriptionSite.setColumns(20);
        jTextAreaDescriptionSite.setRows(5);
        jTextAreaDescriptionSite.setText("Description ...");
        jTextAreaDescriptionSite.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextAreaDescriptionSiteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextAreaDescriptionSiteFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaDescriptionSite);

        jFormattedTextFieldHoraireOuvertureSite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldHoraireOuvertureSite.setToolTipText("Horaire d'ouverture (HH:mm) ...");
        jFormattedTextFieldHoraireOuvertureSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHoraireOuvertureSiteActionPerformed(evt);
            }
        });

        jFormattedTextFieldHoraireFermetureSite.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jFormattedTextFieldHoraireFermetureSite.setToolTipText("Horaire de fermeture (HH:mm) ...");
        jFormattedTextFieldHoraireFermetureSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldHoraireFermetureSiteActionPerformed(evt);
            }
        });

        jTextFieldLatitude.setText("Latitude ...");
        jTextFieldLatitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLatitudeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLatitudeFocusLost(evt);
            }
        });

        jTextFieldLongitude.setText("Longitude ...");
        jTextFieldLongitude.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLongitudeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLongitudeFocusLost(evt);
            }
        });

        jLabelHoraireOuverture.setText("Horaire d'ouverture (HH:mm) :");

        jLabelHoraireFermeture.setText("Horaire de fermeture (HH:mm) :");

        javax.swing.GroupLayout EcranInitialisationSiteLayout = new javax.swing.GroupLayout(EcranInitialisationSite);
        EcranInitialisationSite.setLayout(EcranInitialisationSiteLayout);
        EcranInitialisationSiteLayout.setHorizontalGroup(
            EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitreAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(EcranInitialisationSiteLayout.createSequentialGroup()
                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EcranInitialisationSiteLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jButtonValiderAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EcranInitialisationSiteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EcranInitialisationSiteLayout.createSequentialGroup()
                                .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelSousTitreAssistant, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTitreSite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresseSite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumTelSite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EcranInitialisationSiteLayout.createSequentialGroup()
                                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelHoraireFermeture, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(jLabelHoraireOuverture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextFieldHoraireFermetureSite, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextFieldHoraireOuvertureSite))))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        EcranInitialisationSiteLayout.setVerticalGroup(
            EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranInitialisationSiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreAssistant)
                .addGap(49, 49, 49)
                .addComponent(jLabelSousTitreAssistant)
                .addGap(29, 29, 29)
                .addComponent(jTextFieldTitreSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAdresseSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNumTelSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraireOuverture)
                    .addComponent(jFormattedTextFieldHoraireOuvertureSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EcranInitialisationSiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraireFermeture)
                    .addComponent(jFormattedTextFieldHoraireFermetureSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jButtonValiderAssistant)
                .addContainerGap())
        );

        mainPanel.add(EcranInitialisationSite, "EcranInitialisationSite");

        EcranStats.setPreferredSize(new java.awt.Dimension(800, 600));

        jButtonAccueil.setText("Accueil");
        jButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccueilActionPerformed(evt);
            }
        });

        jTableStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTableStats);

        jLabelStatistique.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelStatistique.setText("Statistiques du musée:");

        javax.swing.GroupLayout EcranStatsLayout = new javax.swing.GroupLayout(EcranStats);
        EcranStats.setLayout(EcranStatsLayout);
        EcranStatsLayout.setHorizontalGroup(
            EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranStatsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabelStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                        .addComponent(jButtonAccueil)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EcranStatsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179))))
        );
        EcranStatsLayout.setVerticalGroup(
            EcranStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EcranStatsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAccueil)
                .addGap(72, 72, 72)
                .addComponent(jLabelStatistique, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        mainPanel.add(EcranStats, "EcranStats");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsulterStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsulterStatsActionPerformed
        //Affichage de l'écran informations bancaires
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "EcranStats");
        SiteDBManager db = new SiteDBManager(this.nombd);
        String nomServiceStat = "STAT " + db.getNomSite();
        //String date = jFormattedTextFieldDateStat.getText();
        String valeurStat;
        try {
            //TODO appel au service E/S du site
            /********* Appel au service statistique du site *********/
            // Construction du nom a rechercher
            /*org.omg.CosNaming.NameComponent[] nameToFind = new org.omg.CosNaming.NameComponent[1];
            nameToFind[0] = new org.omg.CosNaming.NameComponent(nomServiceStat,"");

            // Recherche aupres du naming service
            org.omg.CORBA.Object distantServiceStat = nameRoot.resolve(nameToFind);
            System.out.println("Objet '" + nomServiceStat + "' trouve aupres du service de noms.");

            // Casting de l'objet CORBA
            ServiceStatSite monServiceStat = ServiceStatSiteHelper.narrow(distantServiceStat);

            //Lancement du service ES

            //TODO trouver l'identifiant du site à faire passer en paramètre
            //Récupération des statistiques auprès du service stat
            Statistique[] stat = monServiceStat.getStatsSite(db.getIdSite());*/

            /************ Remplissage du tableau *************/
            //Première ligne
            /*jTableStats.getModel().setValueAt(stat[0].libelleStat,0,0);
            valeurStat=stat[0].valeurStat + " " + stat[0].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,0,1);

            //Deuxième ligne
            jTableStats.getModel().setValueAt(stat[1].libelleStat,1,0);
            valeurStat=stat[1].valeurStat + " " + stat[1].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,1,1);

            //Troisième ligne
            jTableStats.getModel().setValueAt(stat[2].libelleStat,2,0);
            valeurStat=stat[2].valeurStat + " " + stat[2].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,2,1);

            //Quatrième ligne
            jTableStats.getModel().setValueAt(stat[3].libelleStat,3,0);
            valeurStat=stat[3].valeurStat + ' ' + stat[3].uniteStat;
            jTableStats.getModel().setValueAt(valeurStat,3,1);*/

        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonConsulterStatsActionPerformed

    private void jButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccueilActionPerformed
        //Affichage de l'écran d'accueil
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "Accueil");
    }//GEN-LAST:event_jButtonAccueilActionPerformed

    private void jFormattedTextFieldHoraireOuvertureSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHoraireOuvertureSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldHoraireOuvertureSiteActionPerformed

    private void jFormattedTextFieldHoraireFermetureSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHoraireFermetureSiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldHoraireFermetureSiteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // on consulte la bdd pour savoir si c'est le premier lancement de l'application
        try {

            // Connexion
            Connection conn2 = DriverManager.getConnection("jdbc:mysql://localhost/" + nombd, "root", "");
            Statement smt2 = conn2.createStatement();

            ResultSet result = smt2.executeQuery("SELECT estPremierLancement FROM infosite");
            result.first();
            //System.out.println("estPremierLancement" + result.getInt("estPremierLancement"));

            //Lors du lancement de l'application on vérifie en base si c'est le premier lancement
            CardLayout card = (CardLayout) mainPanel.getLayout();
            if (result.getInt("estPremierLancement") == 1) {
                card.show(mainPanel, "EcranInitialisationSite");
            } else {
                card.show(mainPanel, "Accueil");
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void jTextFieldTitreSiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTitreSiteFocusGained
        if (jTextFieldTitreSite.getText().equals("titre du site ...")) {
            jTextFieldTitreSite.setText("");
        }
    }//GEN-LAST:event_jTextFieldTitreSiteFocusGained

    private void jTextFieldTitreSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTitreSiteFocusLost
        if (jTextFieldTitreSite.getText().equals("")) {
            jTextFieldTitreSite.setText("titre du site ...");
        }
    }//GEN-LAST:event_jTextFieldTitreSiteFocusLost

    private void jTextFieldAdresseSiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdresseSiteFocusGained
        if (jTextFieldAdresseSite.getText().equals("adresse du site ...")) {
            jTextFieldAdresseSite.setText("");
        }
    }//GEN-LAST:event_jTextFieldAdresseSiteFocusGained

    private void jTextFieldAdresseSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAdresseSiteFocusLost
        if (jTextFieldAdresseSite.getText().equals("")) {
            jTextFieldAdresseSite.setText("adresse du site ...");
        }
    }//GEN-LAST:event_jTextFieldAdresseSiteFocusLost

    private void jTextFieldNumTelSiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumTelSiteFocusGained
        if (jTextFieldNumTelSite.getText().equals("numéro de téléphone du site ...")) {
            jTextFieldNumTelSite.setText("");
        }
    }//GEN-LAST:event_jTextFieldNumTelSiteFocusGained

    private void jTextFieldNumTelSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumTelSiteFocusLost
        if (jTextFieldNumTelSite.getText().equals("")) {
            jTextFieldNumTelSite.setText("numéro de téléphone du site ...");
        }
    }//GEN-LAST:event_jTextFieldNumTelSiteFocusLost

    private void jTextAreaDescriptionSiteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDescriptionSiteFocusGained
        if (jTextAreaDescriptionSite.getText().equals("Description ...")) {
            jTextAreaDescriptionSite.setText("");
        }
    }//GEN-LAST:event_jTextAreaDescriptionSiteFocusGained

    private void jTextAreaDescriptionSiteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextAreaDescriptionSiteFocusLost
        if (jTextAreaDescriptionSite.getText().equals("")) {
            jTextAreaDescriptionSite.setText("Description ...");
        }
    }//GEN-LAST:event_jTextAreaDescriptionSiteFocusLost

    private void jButtonValiderAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderAssistantActionPerformed
         
        // vérification que tous les champs ont été renseignés ...
        if (jTextFieldTitreSite.getText().equals("titre du site ...")
                || jTextFieldAdresseSite.getText().equals("adresse du site ...")
                || jTextFieldNumTelSite.getText().equals("numéro de téléphone du site ...")
                || jTextAreaDescriptionSite.getText().equals("Description ...")
                || jFormattedTextFieldHoraireOuvertureSite.getText().equals("")
                || jFormattedTextFieldHoraireFermetureSite.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Erreur : \nVeuillez remplir tous les champs !", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else {
            // vérification que l'heure d'ouverture est bien inférieure à l'heure de fermeture ...
            try {
                SimpleDateFormat format = new SimpleDateFormat("HH:mm");
                
                Date dateOuverture = format.parse(jFormattedTextFieldHoraireOuvertureSite.getText());
                Date dateFermeture = format.parse(jFormattedTextFieldHoraireFermetureSite.getText());

                if (dateFermeture.compareTo(dateOuverture) <= 0) {
                    JOptionPane.showMessageDialog(this, "Erreur : \nl'heure d'ouverture doit être inférieure à l'heure de fermeture ! ", "Erreur", JOptionPane.WARNING_MESSAGE);
                } else {
                    // initialisation de la base de données

                    try {
                        
                        // Connexion
                        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/" + nombd, "root", "");
                        Statement smt = conn.createStatement();
                        
                        String requete = "UPDATE infosite SET idSite=2,nomSite=\""
                                + jTextFieldTitreSite.getText().toString()
                                + "\",heureOuverture=\""
                                + jFormattedTextFieldHoraireOuvertureSite.getText().toString()
                                + "\",heureFermeture=\""
                                + jFormattedTextFieldHoraireFermetureSite.getText().toString()
                                + "\",description=\""
                                + jTextAreaDescriptionSite.getText().toString()
                                + "\",adresse=\""
                                + jTextFieldAdresseSite.getText().toString()
                                + "\",telephone=\""
                                + jTextFieldNumTelSite.getText().toString()
                                + "\",estPremierLancement="
                                + 0
                                + " WHERE 1";
                        
                        System.out.println(requete);
                        
                        smt.executeUpdate(requete);
                        
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                    }

                    // on affiche l'accueil
                    CardLayout card = (CardLayout) mainPanel.getLayout();
                    card.show(mainPanel, "Accueil");
                    
                    jLabelTitreAccueil.setText(new SiteDBManager("bd_site_histoirenaturelle").getNomSite());

                }
            } catch (ParseException ex) {
                Logger.getLogger(ClientSiteTouristique.class.getName()).log(Level.SEVERE, null, ex);
            }
        }      
    }//GEN-LAST:event_jButtonValiderAssistantActionPerformed

    private void jTextFieldLatitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLatitudeFocusGained
        if (jTextFieldLatitude.getText().equals("Latitude ...")) {
            jTextFieldLatitude.setText("");
        }
    }//GEN-LAST:event_jTextFieldLatitudeFocusGained

    private void jTextFieldLatitudeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLatitudeFocusLost
        if (jTextFieldLatitude.getText().equals("")) {
            jTextFieldLatitude.setText("Latitude ...");
        }
    }//GEN-LAST:event_jTextFieldLatitudeFocusLost

    private void jTextFieldLongitudeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLongitudeFocusGained
        if (jTextFieldLongitude.getText().equals("Longitude ...")) {
            jTextFieldLongitude.setText("");
        }
    }//GEN-LAST:event_jTextFieldLongitudeFocusGained

    private void jTextFieldLongitudeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLongitudeFocusLost
        if (jTextFieldLongitude.getText().equals("")) {
            jTextFieldLongitude.setText("Longitude ...");
        }
    }//GEN-LAST:event_jTextFieldLongitudeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSiteTouristique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSiteTouristique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSiteTouristique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSiteTouristique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //System.out.println(args[0]);
        
        //ClientSiteTouristique.setNombd(args[0]);
        try {
            
            //1
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init(args, null);
            
            //2 
            nameRoot = org.omg.CosNaming.NamingContextHelper.narrow(orb.resolve_initial_references("NameService"));
            
            //Lancement du serveur du site
            /*ServeurSite servSite = new ServeurSite(nombd, args);
            Thread thread_Site = new Thread(servSite);
            thread_Site.start();
            
            //Lancement du serveur du service ES
            ServeurServiceESSite servESSite = new ServeurServiceESSite(nombd, args);
            Thread thread_servESSite = new Thread(servESSite);
            thread_servESSite.start();
            
            //Lancement du serveur stat
            ServeurStatSite servStatSite = new ServeurStatSite(nombd, args);
            Thread thread_servStatSite = new Thread(servStatSite);
            thread_servStatSite.start();*/
            
            //Appel à l'interface graphique
            ClientSiteTouristique client = new ClientSiteTouristique(args[0]);
            client.setVisible(true);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Accueil;
    private javax.swing.JPanel EcranInitialisationSite;
    private javax.swing.JPanel EcranStats;
    private javax.swing.JButton jButtonAccueil;
    private javax.swing.JButton jButtonConsulterStats;
    private javax.swing.JButton jButtonValiderAssistant;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraireFermetureSite;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraireOuvertureSite;
    private javax.swing.JLabel jLabelHoraireFermeture;
    private javax.swing.JLabel jLabelHoraireOuverture;
    private javax.swing.JLabel jLabelSousTitreAssistant;
    private javax.swing.JLabel jLabelStatistique;
    private javax.swing.JLabel jLabelTitreAccueil;
    private javax.swing.JLabel jLabelTitreAssistant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStats;
    private javax.swing.JTextArea jTextAreaDescriptionSite;
    private javax.swing.JTextField jTextFieldAdresseSite;
    private javax.swing.JTextField jTextFieldLatitude;
    private javax.swing.JTextField jTextFieldLongitude;
    private javax.swing.JTextField jTextFieldNumTelSite;
    private javax.swing.JTextField jTextFieldTitreSite;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
